name = "kitab"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A hugo theme for publishing books"
homepage = ""
tags = ["book"]
features = ["minimal", "responsive"]
min_version = "0.41"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"